import json
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ZHS = ROOT / "Komeiji_Koishi" / "localization" / "zhs"
ENG = ROOT / "Komeiji_Koishi" / "localization" / "eng"
LONG_NAMES = ROOT / "Komeiji_Koishi" / "localization" / "eng_long_name_options.md"


def ordered(items):
    return OrderedDict(items)


translations = {
    "card_keywords.json": ordered([
        ("KOMEIJIKOISHI-UNCONSCIOUS.title", "Unconscious"),
        ("KOMEIJIKOISHI-UNCONSCIOUS.description", "Cards with this tag can be played by unconscious effects."),
        ("KOMEIJIKOISHI-BLOOM.title", "Bloom"),
        ("KOMEIJIKOISHI-BLOOM.description", "When you play an Attack, deal extra damage equal to that card's damage to a random enemy. [gold]Block[/gold] you gain is reduced by 60%. Gain energy when entering this stance."),
        ("KOMEIJIKOISHI-CLOSED.title", "Closed"),
        ("KOMEIJIKOISHI-CLOSED.description", "[gold]Block[/gold] you gain is increased by 20%. Draw 1 card when entering this stance."),
        ("KOMEIJIKOISHI-DANMAKU.title", "Danmaku"),
        ("KOMEIJIKOISHI-DANMAKU.description", "Generated cards with various effects."),
        ("KOMEIJIKOISHI-STANCE.title", "Stance"),
        ("KOMEIJIKOISHI-STANCE.description", "[blue]Closed[/blue] and [red]Bloom[/red] stances have special effects when entered."),
        ("KOMEIJIKOISHI-FUMO.title", "Fumo"),
        ("KOMEIJIKOISHI-FUMO.description", "Rulers of the world with mysterious powers."),
        ("KOMEIJIKOISHI-LOST_IN_FLOWER_FIELD.title", "Lost in the Flower Field"),
        ("KOMEIJIKOISHI-LOST_IN_FLOWER_FIELD.description", "[green]Koishi[/green] is on an adventure. The flower field is [purple]purple[/purple], [blue]blue[/blue], and [red]red[/red]. Relax. [thinky_dots]Empty your head[/thinky_dots]."),
    ]),
    "characters.json": ordered([
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.aromaPrinciple", "[sine][blue]I feel like someone stared at me like this before.[/blue][/sine]"),
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.banter.alive.endTurnPing", "Koishi is waiting~"),
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.banter.dead.endTurnPing", "Zzz"),
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.cardsModifierDescription", "Koishi Komeiji's cards can now appear in rewards and shops."),
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.cardsModifierTitle", "Koishi Komeiji Cards"),
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.description", "An unconscious satori youkai who wandered into the Spire and began her adventure."),
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.eventDeathPrevention", "If I fall down, I can't keep adventuring."),
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.goldMonologue", "[sine]So many shiny things! I think Okuu likes collecting these.[/sine]"),
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.possessiveAdjective", "her"),
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.pronounObject", "her"),
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.pronounPossessive", "hers"),
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.pronounSubject", "she"),
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.title", "Koishi Komeiji"),
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.titleObject", "Koishi Komeiji"),
        ("KOMEIJIKOISHI-KOISHI_CHARACTER.unlockText", "Play a run with [pink]{Prerequisite}[/pink] to unlock this character."),
    ]),
    "enchantments.json": ordered([
        ("KOMEIJIKOISHI-ZI_ZAI_ENCHANTMENT.title", "At Ease"),
        ("KOMEIJIKOISHI-ZI_ZAI_ENCHANTMENT.extraCardText", "At the start of combat, gain [gold]Unconscious[/gold]."),
        ("KOMEIJIKOISHI-ZI_ZAI_ENCHANTMENT.description", "At the start of the first turn of combat, this card gains [gold]Unconscious[/gold]."),
        ("KOMEIJIKOISHI-MIRACLE_ENCHANTMENT.title", "Miracle"),
        ("KOMEIJIKOISHI-MIRACLE_ENCHANTMENT.extraCardText", "When played, gain {Energy:energyIcons()}, then [gold]Exhaust[/gold]."),
        ("KOMEIJIKOISHI-MIRACLE_ENCHANTMENT.description", "When you play this card, gain {Energy:energyIcons()}, then [gold]Exhaust[/gold]."),
        ("KOMEIJIKOISHI-FLYING_ENCHANTMENT.title", "Flying"),
        ("KOMEIJIKOISHI-FLYING_ENCHANTMENT.extraCardText", "When played, reduce damage taken this turn by 50%."),
        ("KOMEIJIKOISHI-FLYING_ENCHANTMENT.description", "When you play this card, reduce damage taken this turn by 50%."),
    ]),
    "gameplay_ui.json": ordered([
        ("CARD.KOMEIJIKOISHI-ENTER_DREAM_KOISHI.prompt", "Choose 1 card to put into your hand"),
    ]),
    "powers.json": ordered([
        ("KOMEIJIKOISHI-ULTIMATE_UNCONSCIOUS_FORM_POWER.title", "Ultimate Unconscious"),
        ("KOMEIJIKOISHI-ULTIMATE_UNCONSCIOUS_FORM_POWER.smartDescription", "When you manually play a card, automatically play {Amount} Unconscious cards from your hand. Whenever you play an Unconscious card, draw 1 card."),
        ("KOMEIJIKOISHI-BLOOM_STANCE_POWER.title", "Bloom"),
        ("KOMEIJIKOISHI-BLOOM_STANCE_POWER.smartDescription", "When you play an Attack, deal extra damage equal to that card's damage to a random enemy. [gold]Block[/gold] you gain is reduced by {BlockReduction}%. When entering this stance, gain {Amount:energyIcons()}."),
        ("KOMEIJIKOISHI-BLOOM_STANCE_POWER.description", "When you play an Attack, deal extra damage equal to that card's damage to a random enemy. [gold]Block[/gold] you gain is reduced by 70%. When entering this stance, gain {energyPrefix:energyIcons(1)}."),
        ("KOMEIJIKOISHI-CLOSED_STANCE_POWER.title", "Closed"),
        ("KOMEIJIKOISHI-CLOSED_STANCE_POWER.smartDescription", "[gold]Block[/gold] you gain is increased by {BlockBonus}%. Draw 1 card when entering this stance."),
        ("KOMEIJIKOISHI-CLOSED_STANCE_POWER.description", "[gold]Block[/gold] you gain is increased by 20%. Draw 1 card when entering this stance."),
        ("KOMEIJIKOISHI-FETUS_DREAM_POWER.title", "Fetus Dream"),
        ("KOMEIJIKOISHI-FETUS_DREAM_POWER.smartDescription", "[gold]Unconscious[/gold] has expanded!"),
        ("KOMEIJIKOISHI-TRACING_POWER.title", "Tracing"),
        ("KOMEIJIKOISHI-TRACING_POWER.smartDescription", "Take 50% more attack damage from [gold]Danmaku[/gold]."),
        ("KOMEIJIKOISHI-TRACING_POWER.description", "Take 50% more attack damage from [gold]Danmaku[/gold]."),
        ("KOMEIJIKOISHI-DANMAKU_ART_POWER.title", "Danmaku Art"),
        ("KOMEIJIKOISHI-DANMAKU_ART_POWER.smartDescription", "Whenever you play a [gold]Danmaku[/gold] card, gain {Amount} [gold]Block[/gold]."),
        ("KOMEIJIKOISHI-RECOGNIZED_GENIUS_POWER.title", "Recognized Genius"),
        ("KOMEIJIKOISHI-RECOGNIZED_GENIUS_POWER.smartDescription", "[gold]Danmaku[/gold] cards you generate during combat are automatically upgraded."),
        ("KOMEIJIKOISHI-SUPEREGO_POWER.title", "Superego"),
        ("KOMEIJIKOISHI-SUPEREGO_POWER.smartDescription", "When you enter [gold]Closed[/gold], draw {Amount} additional card(s). When you enter [gold]Bloom[/gold], gain {Amount:energyIcons()} additional energy."),
        ("KOMEIJIKOISHI-MENTAL_STELLAR_SUCCESSION_POWER.title", "Mental Stellar Succession"),
        ("KOMEIJIKOISHI-MENTAL_STELLAR_SUCCESSION_POWER.smartDescription", "This combat, [gold]Tracing[/gold]'s damage bonus is increased by {Amount}%."),
        ("KOMEIJIKOISHI-KOISHI_KOKORO_POWER.title", "Kokoro's Mask"),
        ("KOMEIJIKOISHI-KOISHI_KOKORO_POWER.smartDescription", "When you switch stances, randomly trigger an [red]emo[/red][orange]tion[/orange]."),
        ("KOMEIJIKOISHI-JOY_MASK_POWER.title", "Mask of Joy"),
        ("KOMEIJIKOISHI-JOY_MASK_POWER.smartDescription", "Your next {Amount} card(s) cost 0."),
        ("KOMEIJIKOISHI-REIMU_HELP_POWER.title", "Reimu's Help"),
        ("KOMEIJIKOISHI-REIMU_HELP_POWER.smartDescription", "Whenever you draw [gold]Yin-Yang Orb Danmaku[/gold], automatically play it. [gold]Yin-Yang Orb Danmaku[/gold] damage is increased by {Amount}%."),
        ("KOMEIJIKOISHI-ROSE_PROTECTION_POWER.title", "Rose Protection"),
        ("KOMEIJIKOISHI-ROSE_PROTECTION_POWER.smartDescription", "While in [gold]Closed[/gold], [gold]Block[/gold] you gain is increased by {Amount}%."),
        ("KOMEIJIKOISHI-MIRACLE_POWER.title", "Miracle"),
        ("KOMEIJIKOISHI-MIRACLE_POWER.smartDescription", "Whenever you play a [gold]Danmaku[/gold] card, play that card {Amount} additional time(s)."),
        ("KOMEIJIKOISHI-KUUGA_POWER.title", "Kuuga"),
        ("KOMEIJIKOISHI-KUUGA_POWER.smartDescription", "Your 0-cost Attack cards deal {Amount:cond:<0?reduced|increased} damage by [blue]{Amount:abs()}[/blue]."),
        ("KOMEIJIKOISHI-KUUGA_POWER.description", "Your 0-cost Attack cards deal {Amount:cond:<0?reduced|increased} damage by [blue]{Amount:abs()}[/blue]."),
        ("KOMEIJIKOISHI-SECOND_NEED_POWER.title", "Second Need"),
        ("KOMEIJIKOISHI-SECOND_NEED_POWER.smartDescription", "Whenever you switch stances, gain {Amount} Block."),
        ("KOMEIJIKOISHI-UNDERGROUND_ROSE_POWER.title", "Underground Rose"),
        ("KOMEIJIKOISHI-UNDERGROUND_ROSE_POWER.smartDescription", "Whenever you switch stances, generate and automatically play {Amount} [gold]Rose Danmaku[/gold]."),
        ("KOMEIJIKOISHI-CONSCIOUSNESS_SPIRAL_POWER.title", "Consciousness Spiral"),
        ("KOMEIJIKOISHI-CONSCIOUSNESS_SPIRAL_POWER.smartDescription", "At the start of your turn, add {Amount} [gold]Conscious Spin[/gold] to your hand."),
        ("KOMEIJIKOISHI-PHILOSOPHY_OF_THE_HATED_POWER.title", "Philosophy of the Hated"),
        ("KOMEIJIKOISHI-PHILOSOPHY_OF_THE_HATED_POWER.smartDescription", "Whenever you enter [gold]Closed[/gold], automatically play {Amount} [gold]Unconscious[/gold] card(s) from your hand."),
        ("KOMEIJIKOISHI-SELFLESS_LOVE_POWER.title", "Selfless Love"),
        ("KOMEIJIKOISHI-SELFLESS_LOVE_POWER.smartDescription", "Whenever you generate 6 Danmaku cards, draw {Amount} card(s)."),
        ("KOMEIJIKOISHI-FLAW_OF_DN_A_POWER.title", "Flaw of DNA"),
        ("KOMEIJIKOISHI-FLAW_OF_DN_A_POWER.smartDescription", "All your Attack cards cost 0 and [gold]Exhaust[/gold] when played."),
        ("KOMEIJIKOISHI-BRAMBLY_ROSE_GARDEN_POWER.title", "Brambly Rose Garden"),
        ("KOMEIJIKOISHI-BRAMBLY_ROSE_GARDEN_POWER.smartDescription", "At the start of your turn, your [gold]Thorns[/gold] are increased by {Amount}00%."),
        ("KOMEIJIKOISHI-INSTINCTIVE_FORM_POWER.title", "Instinctive Form"),
        ("KOMEIJIKOISHI-INSTINCTIVE_FORM_POWER.smartDescription", "At the end of your turn, randomly play {Amount} [gold]Unconscious[/gold] card(s) from your hand."),
        ("KOMEIJIKOISHI-PERFECT_MIND_CONTROL_POWER.title", "Mind Control"),
        ("KOMEIJIKOISHI-PERFECT_MIND_CONTROL_POWER.smartDescription", "The next {Amount} [gold]Unconscious[/gold] card(s) you draw are automatically played."),
        ("KOMEIJIKOISHI-FLAW_POWER.title", "Flaw"),
        ("KOMEIJIKOISHI-FLAW_POWER.smartDescription", "At the start of your turn, all 0-cost Attack cards deal {Amount} less damage."),
        ("KOMEIJIKOISHI-LOST_IN_FLOWER_FIELD_POWER.title", "Lost in Flower Field"),
        ("KOMEIJIKOISHI-LOST_IN_FLOWER_FIELD_POWER.smartDescription", "At the start of your turn, randomly return {Amount} card(s) generated by [gold]Lost in the Flower Field[/gold] from your exhaust pile to your hand."),
        ("KOMEIJIKOISHI-JIASUI_POWER.title", "Evil Omen"),
        ("KOMEIJIKOISHI-JIASUI_POWER.smartDescription", "When triggered, lose HP equal to its stacks and give other enemies that many [gold]Evil Omen[/gold]."),
        ("KOMEIJIKOISHI-JIASUI_POWER.description", "When triggered, lose HP equal to its stacks and give other enemies that many [gold]Evil Omen[/gold]."),
        ("KOMEIJIKOISHI-FLYING_DAMAGE_REDUCTION_POWER.title", "Flying"),
        ("KOMEIJIKOISHI-FLYING_DAMAGE_REDUCTION_POWER.smartDescription", "Damage taken this turn is reduced by 50%."),
        ("KOMEIJIKOISHI-FLYING_DAMAGE_REDUCTION_POWER.description", "Damage taken this turn is reduced by 50%."),
        ("KOMEIJIKOISHI-GUARDIAN_POWER.title", "Guardian"),
        ("KOMEIJIKOISHI-GUARDIAN_POWER.smartDescription", "Cannot receive debuffs. Lose 1 stack at the start of each turn."),
        ("KOMEIJIKOISHI-GUARDIAN_POWER.description", "Cannot receive debuffs. Lose 1 stack at the start of each turn."),
    ]),
}

cards = ordered([
("KOMEIJIKOISHI-STRIKE_KOISHI.title", "Strike"),
("KOMEIJIKOISHI-STRIKE_KOISHI.description", "Deal {Damage:diff()} damage."),
("KOMEIJIKOISHI-DEFEND_KOISHI.title", "Defend"),
("KOMEIJIKOISHI-DEFEND_KOISHI.description", "Gain {Block:diff()} [gold]Block[/gold]."),
("KOMEIJIKOISHI-INSTINCTIVE_STAB_KOISHI.title", "Instinctive Stab"),
("KOMEIJIKOISHI-INSTINCTIVE_STAB_KOISHI.description", "Deal {Damage:diff()} damage {Repeat:diff()} times."),
("KOMEIJIKOISHI-ROAMING_KOISHI.title", "Roaming"),
("KOMEIJIKOISHI-ROAMING_KOISHI.description", "Gain {Block:diff()} [gold]Block[/gold].\nRandomly choose {Amount:diff()} card(s) in your hand. They gain [gold]Unconscious[/gold] for this combat."),
("CARD.KOMEIJIKOISHI-ROAMING_KOISHI.prompt", "Choose a card to gain Unconscious."),
("KOMEIJIKOISHI-ARTWORK_KOISHI.title", "Artwork"),
("KOMEIJIKOISHI-ARTWORK_KOISHI.description", "Deal {Damage:diff()} damage.\nGain {Block:diff()} [gold]Block[/gold]."),
("KOMEIJIKOISHI-ARTWORK_KOISHI.flavor", "A work of art for both attack and defense."),
("KOMEIJIKOISHI-COMPLETE_UNCONSCIOUS_KOISHI.title", "Complete Unconscious"),
("KOMEIJIKOISHI-COMPLETE_UNCONSCIOUS_KOISHI.description", "Gain {IntangiblePower:diff()} [gold]Intangible[/gold].\n[thinky_dots][orange]5[/orange][purple]1[/purple][green]4[/green] cannot be [red]changed[/red][/thinky_dots]"),
("KOMEIJIKOISHI-COMPLETE_UNCONSCIOUS_KOISHI.flavor", "Complete unconsciousness. No one knows what will happen."),
("KOMEIJIKOISHI-ULTIMATE_UNCONSCIOUS_FORM_KOISHI.title", "Ultimate Unconscious Form"),
("KOMEIJIKOISHI-ULTIMATE_UNCONSCIOUS_FORM_KOISHI.description", "Whenever you manually play a card, automatically play {FormAmount:diff()} [gold]Unconscious[/gold] card(s) from your hand.\nWhenever you play an [gold]Unconscious[/gold] card, draw 1 card. This draw does not stack."),
("KOMEIJIKOISHI-ULTIMATE_UNCONSCIOUS_FORM_KOISHI.flavor", "Close the eye of consciousness completely and let instinct control this body through every battle."),
("KOMEIJIKOISHI-ROSE_BLOOM_KOISHI.title", "Rose Bloom"),
("KOMEIJIKOISHI-ROSE_BLOOM_KOISHI.description", "Deal {Damage:diff()} damage.\nEnter [gold]Bloom[/gold]."),
("KOMEIJIKOISHI-HEART_CLOSED_KOISHI.title", "Heart Closed"),
("KOMEIJIKOISHI-HEART_CLOSED_KOISHI.description", "Gain {Block:diff()} [gold]Block[/gold].\nEnter [gold]Closed[/gold]."),
("KOMEIJIKOISHI-KOMEIJI_SPIN_KOISHI.title", "Komeiji Spin"),
("KOMEIJIKOISHI-KOMEIJI_SPIN_KOISHI.description", "Deal {Damage:diff()} damage to all enemies {Repeat:diff()} times."),
("KOMEIJIKOISHI-FETUS_DREAM_KOISHI.title", "Fetus Dream"),
("KOMEIJIKOISHI-FETUS_DREAM_KOISHI.description", "For this combat, cards with 'Unconscious' or 'Instinctive' in their names are also treated as [gold]Unconscious[/gold]."),
("KOMEIJIKOISHI-HEART_DANMAKU_KOISHI.title", "Heart Danmaku"),
("KOMEIJIKOISHI-HEART_DANMAKU_KOISHI.description", "Deal {Damage:diff()} damage. Apply {WeakPower:diff()} [gold]Weak[/gold]."),
("KOMEIJIKOISHI-STAR_DANMAKU_KOISHI.title", "Star Danmaku"),
("KOMEIJIKOISHI-STAR_DANMAKU_KOISHI.description", "Deal {Damage:diff()} damage."),
("KOMEIJIKOISHI-YIN_YANG_ORB_DANMAKU_KOISHI.title", "Yin-Yang Orb Danmaku"),
("KOMEIJIKOISHI-YIN_YANG_ORB_DANMAKU_KOISHI.description", "Deal {Damage:diff()} damage."),
("KOMEIJIKOISHI-RICE_DANMAKU_KOISHI.title", "Rice Danmaku"),
("KOMEIJIKOISHI-RICE_DANMAKU_KOISHI.description", "Deal {Damage:diff()} damage. Add 2 copies of this card to your exhaust pile."),
("KOMEIJIKOISHI-SMALL_ORB_DANMAKU_KOISHI.title", "Small Orb Danmaku"),
("KOMEIJIKOISHI-SMALL_ORB_DANMAKU_KOISHI.description", "Deal {Damage:diff()} damage {Repeat:diff()} times."),
("KOMEIJIKOISHI-LARGE_ORB_DANMAKU_KOISHI.title", "Large Orb Danmaku"),
("KOMEIJIKOISHI-LARGE_ORB_DANMAKU_KOISHI.description", "Deal {Damage:diff()} damage. Apply {VulnerablePower:diff()} [gold]Vulnerable[/gold]."),
("KOMEIJIKOISHI-ARROW_DANMAKU_KOISHI.title", "Arrow Danmaku"),
("KOMEIJIKOISHI-ARROW_DANMAKU_KOISHI.description", "Deal {Damage:diff()} damage to all enemies."),
("KOMEIJIKOISHI-SQUARE_DANMAKU_KOISHI.title", "Square Danmaku"),
("KOMEIJIKOISHI-SQUARE_DANMAKU_KOISHI.description", "Deal {Damage:diff()} damage. Apply {TracingPower:diff()} [gold]Tracing[/gold]."),
("KOMEIJIKOISHI-NON_SPELL_CARD_KOISHI.title", "Non-Spell Card"),
("KOMEIJIKOISHI-NON_SPELL_CARD_KOISHI.description", "Add {Cards:diff()} random [gold]Danmaku[/gold] card(s) to your hand."),
("KOMEIJIKOISHI-UNCONSCIOUS_DANMAKU_ATTACK_KOISHI.title", "Unconscious Danmaku"),
("KOMEIJIKOISHI-UNCONSCIOUS_DANMAKU_ATTACK_KOISHI.description", "Randomly generate and automatically play {Cards:diff()} [gold]Danmaku[/gold] card(s)."),
("KOMEIJIKOISHI-UNCONSCIOUS_DANMAKU_ATTACK_KOISHI.flavor", "Danmaku etiquette should begin with both sides agreeing. This, however, is just danmaku thrown by the unconscious."),
("KOMEIJIKOISHI-SUBCONSCIOUS_RELEASE_KOISHI.title", "Subconscious Release"),
("KOMEIJIKOISHI-SUBCONSCIOUS_RELEASE_KOISHI.description", "Randomly play {Cards:diff()} [gold]Danmaku[/gold] card(s) from your [gold]exhaust pile[/gold]."),
("KOMEIJIKOISHI-REACTION_YOUKAI_POLYGRAPH_KOISHI.title", "Reaction: Youkai Polygraph"),
("KOMEIJIKOISHI-REACTION_YOUKAI_POLYGRAPH_KOISHI.description", "Enter [gold]Bloom[/gold].\nIf the target enemy intends to attack, draw {Draw:diff()} card(s)."),
("KOMEIJIKOISHI-ENTER_DREAM_KOISHI.selectionScreenPrompt", "Choose 1 card to put into your hand"),
("KOMEIJIKOISHI-ENTER_DREAM_KOISHI.title", "Enter Dream"),
("KOMEIJIKOISHI-ENTER_DREAM_KOISHI.description", "Enter [gold]Closed[/gold].\nChoose 1 card from your discard pile and put it into your hand."),
("KOMEIJIKOISHI-HEART_ANGER_KOISHI.title", "Heart Anger"),
("KOMEIJIKOISHI-HEART_ANGER_KOISHI.description", "Deal {Damage:diff()} damage. Enter [gold]Bloom[/gold]. If you are in [gold]Closed[/gold], this card costs 1."),
("KOMEIJIKOISHI-UNCONSCIOUS_PASSAGE_KOISHI.title", "Unconscious Passage"),
("KOMEIJIKOISHI-UNCONSCIOUS_PASSAGE_KOISHI.description", "[gold]Block[/gold] is not lost for the next {Blur:diff()} turn(s).\nEnter [gold]Closed[/gold]."),
("KOMEIJIKOISHI-DANMAKU_PARANOIA_KOISHI.title", "Danmaku Paranoia"),
("KOMEIJIKOISHI-DANMAKU_PARANOIA_KOISHI.description", "Exhaust all non-[gold]Unconscious[/gold] cards in your hand. For each card exhausted this way, add a random [gold]Danmaku[/gold] card to your hand."),
("KOMEIJIKOISHI-DANMAKU_ART_KOISHI.title", "Danmaku Art"),
("KOMEIJIKOISHI-DANMAKU_ART_KOISHI.description", "Whenever you play a [gold]Danmaku[/gold] card, gain {ArtAmount:diff()} [gold]Block[/gold]."),
("KOMEIJIKOISHI-DANMAKU_RORSCHACH_KOISHI.title", "Danmaku Rorschach"),
("KOMEIJIKOISHI-DANMAKU_RORSCHACH_KOISHI.description", "Play all [gold]Danmaku[/gold] cards in your hand, draw pile, discard pile, and exhaust pile."),
("KOMEIJIKOISHI-RECOGNIZED_GENIUS_KOISHI.title", "Recognized Genius"),
("KOMEIJIKOISHI-RECOGNIZED_GENIUS_KOISHI.description", "Upgrade all [gold]Danmaku[/gold].\nAll 0{energyPrefix:energyIcons(1)} Attack cards deal {KuugaPower:diff()} more damage."),
("KOMEIJIKOISHI-ANCESTORS_DREAM_KOISHI.title", "Ancestors' Dream"),
("KOMEIJIKOISHI-ANCESTORS_DREAM_KOISHI.description", "Copy all cards in your [gold]exhaust pile[/gold] and put the copies into your [gold]exhaust pile[/gold]."),
("KOMEIJIKOISHI-SUPEREGO_KOISHI.title", "Superego"),
("KOMEIJIKOISHI-SUPEREGO_KOISHI.description", "When you enter [gold]Closed[/gold], draw 1 additional card. When you enter [gold]Bloom[/gold], gain {Energy:energyIcons()} additional energy."),
("KOMEIJIKOISHI-BURIED_FIRE_KOISHI.title", "Buried Fire"),
("KOMEIJIKOISHI-BURIED_FIRE_KOISHI.description", "Deal {Damage:diff()} damage.\nPlay and [gold]Exhaust[/gold] all cards in your discard pile. For each card played this way, apply {Tracing:diff()} [gold]Tracing[/gold] to all enemies."),
("KOMEIJIKOISHI-STINGING_MIND_KOISHI.title", "Stinging Mind"),
("KOMEIJIKOISHI-STINGING_MIND_KOISHI.description", "Deal {Damage:diff(} damage.\nRandomly play 2 [gold]Unconscious[/gold] cards from your hand."),
("KOMEIJIKOISHI-PAINFUL_GROWTH_KOISHI.title", "Painful Growth"),
("KOMEIJIKOISHI-PAINFUL_GROWTH_KOISHI.description", "Randomly play {Amount:diff()} [gold]Unconscious[/gold] card(s) from your hand."),
("KOMEIJIKOISHI-ROSE_DANMAKU_KOISHI.title", "Rose Danmaku"),
("KOMEIJIKOISHI-ROSE_DANMAKU_KOISHI.description", "Deal {Damage:diff()} damage.\nGain {Thorns:diff()} [gold]Thorns[/gold]."),
("KOMEIJIKOISHI-ROSE_HELL_KOISHI.title", "Rose Hell"),
("KOMEIJIKOISHI-ROSE_HELL_KOISHI.description", "For every {Threshold:diff()} card(s) in your exhaust pile, add 1 [gold]Rose Danmaku[/gold] to your hand."),
("KOMEIJIKOISHI-EMPTY_HEAD_KOISHI.title", "Empty Head"),
("KOMEIJIKOISHI-EMPTY_HEAD_KOISHI.description", "Gain {Block:diff()} Block.\nRandomly give a card in your hand [gold]Unconscious[/gold]."),
("KOMEIJIKOISHI-UNINTENTIONAL_DANMAKU_KOISHI.title", "Unintentional Danmaku"),
("KOMEIJIKOISHI-UNINTENTIONAL_DANMAKU_KOISHI.description", "Gain {Block:diff()} Block.\nAdd {Amount:diff()} random [gold]Danmaku[/gold] card(s) to your hand."),
("KOMEIJIKOISHI-LOVE_TRAIN_KOISHI.title", "Love Train"),
("KOMEIJIKOISHI-LOVE_TRAIN_KOISHI.description", "Gain {Block:diff()} Block.\nAdd 1 [gold]Yin-Yang Orb Danmaku[/gold] to your hand."),
("KOMEIJIKOISHI-STARE_KOISHI.title", "Stare"),
("KOMEIJIKOISHI-STARE_KOISHI.description", "Deal {Damage:diff()} damage.\nApply {VulnerablePower:diff()} [gold]Vulnerable[/gold].\nDraw {Cards:diff()} card(s)."),
("KOMEIJIKOISHI-INNER_AIM_KOISHI.title", "Inner Aim"),
("KOMEIJIKOISHI-INNER_AIM_KOISHI.description", "Apply {Tracing:diff()} [gold]Tracing[/gold].\nAll 0{energyPrefix:energyIcons(1)} Attack cards deal {KuugaPower:diff()} more damage."),
("KOMEIJIKOISHI-MENTAL_STELLAR_SUCCESSION_KOISHI.title", "Mental Stellar Succession"),
("KOMEIJIKOISHI-MENTAL_STELLAR_SUCCESSION_KOISHI.description", "[gold]Tracing[/gold]'s damage bonus is increased by {Multiplier:diff()}%."),
("KOMEIJIKOISHI-TURN_AROUND_DODGE_KOISHI.title", "Turnaround Dodge"),
("KOMEIJIKOISHI-TURN_AROUND_DODGE_KOISHI.description", "Gain {Block:diff()} Block.\nRandomly play a [gold]Unconscious[/gold] card from your hand."),
("KOMEIJIKOISHI-DISINTEGRATING_CONSCIOUSNESS_CAPTURE_KOISHI.title", "Unconscious Capture"),
("KOMEIJIKOISHI-DISINTEGRATING_CONSCIOUSNESS_CAPTURE_KOISHI.description", "Deal {Damage:diff()} damage.\nThis card costs {energyPrefix:energyIcons(1)} less for each [gold]Unconscious[/gold] card in your discard pile."),
("KOMEIJIKOISHI-JOYFUL_DANCE_KOISHI.title", "Joyful Dance"),
("KOMEIJIKOISHI-JOYFUL_DANCE_KOISHI.description", "Gain {Block:diff()} [gold]Block[/gold].\nEnter [gold]Bloom[/gold].\nDraw {Cards:diff()} card(s)."),
("KOMEIJIKOISHI-KOISHI_KOKORO_AND_UNCONSCIOUS_KOISHI.title", "Koishi, Kokoro, and Unconscious"),
("KOMEIJIKOISHI-KOISHI_KOKORO_AND_UNCONSCIOUS_KOISHI.description", "When you switch [gold]Stances[/gold], randomly gain one of the following effects:\n[gold]Joy[/gold]: Your next {JoyMaskPower:diff()} card(s) cost 0.\n[gold]Anger[/gold]: Gain {StrengthPower:diff()} [gold]Strength[/gold].\n[gold]Sorrow[/gold]: Gain {DexterityPower:diff()} [gold]Dexterity[/gold].\n[gold]Happiness[/gold]: Draw {Cards:diff()} card(s)."),
("KOMEIJIKOISHI-ID_LIBERATION_KOISHI.title", "Instinctive Id Liberation"),
("KOMEIJIKOISHI-ID_LIBERATION_KOISHI.description", "Deal {Damage:diff()} damage {Repeat:diff()} times.\nPlay all [gold]Unconscious[/gold] cards in your hand."),
("KOMEIJIKOISHI-INSTINCT_STRIKE_KOISHI.title", "Instinctive Strike"),
("KOMEIJIKOISHI-INSTINCT_STRIKE_KOISHI.description", "Deal {Damage:diff()} damage. Choose a card in your hand. It gains [gold]Unconscious[/gold]."),
("KOMEIJIKOISHI-INSTINCT_STRIKE_KOISHI.selectionScreenPrompt", "Choose a card to gain Unconscious"),
("KOMEIJIKOISHI-HIDDEN_CONSCIOUSNESS_KOISHI.title", "Hidden Consciousness"),
("KOMEIJIKOISHI-HIDDEN_CONSCIOUSNESS_KOISHI.description", "Gain {Block:diff()} Block.\nGenerate {Magic:diff()} random [gold]Danmaku[/gold] cards and put them into your [gold]exhaust pile[/gold].\nRandomly play {Cards:diff()} [gold]Danmaku[/gold] card(s) from your [gold]exhaust pile[/gold]."),
("KOMEIJIKOISHI-BIG_HUG_KOISHI.title", "Koishi Big Hug"),
("KOMEIJIKOISHI-BIG_HUG_KOISHI.description", "Deal {Damage:diff()} damage.\nGain {energyPrefix:energyIcons(1)} for each [gold]Unconscious[/gold] card in your discard pile, up to {energyPrefix:energyIcons(4)}."),
("KOMEIJIKOISHI-SELF_OVERFLOW_KOISHI.title", "Self Overflow"),
("KOMEIJIKOISHI-SELF_OVERFLOW_KOISHI.description", "Gain {Energy:energyIcons()} and generate {Cards:diff()} [gold]Conscious Overflow[/gold]."),
("KOMEIJIKOISHI-CONSCIOUS_OVERFLOW_KOISHI.title", "Conscious Overflow"),
("KOMEIJIKOISHI-CONSCIOUS_OVERFLOW_KOISHI.description", "[sine]You're thinking too much~[/sine] {IfUpgraded:show:[sine]\nWay too much~[/sine]}"),
("KOMEIJIKOISHI-REIMU_HELP_KOISHI.title", "Reimu's Help"),
("KOMEIJIKOISHI-REIMU_HELP_KOISHI.description", "Whenever you draw [gold]Yin-Yang Orb Danmaku[/gold], automatically play it.\nGenerate {Orbs:diff()} [gold]Yin-Yang Orb Danmaku[/gold] into your draw pile.\nAll [gold]Yin-Yang Orb Danmaku[/gold] deal 20% more damage."),
("KOMEIJIKOISHI-ROSE_PROTECTION_KOISHI.title", "Rose Protection"),
("KOMEIJIKOISHI-ROSE_PROTECTION_KOISHI.description", "While in [gold]Closed[/gold], [gold]Block[/gold] you gain is increased by {Rose:diff()}%."),
("KOMEIJIKOISHI-AIR_STRIKE_KOISHI.title", "Air Strike"),
("KOMEIJIKOISHI-AIR_STRIKE_KOISHI.description", "Deal {Damage:diff()} damage. Whenever you play an [gold]Unconscious[/gold] card, if this card is not in the exhaust pile, add it to your hand."),
("KOMEIJIKOISHI-KUUGA_STRIKE_KOISHI.title", "Kuuga Strike"),
("KOMEIJIKOISHI-KUUGA_STRIKE_KOISHI.description", "Deal {Damage:diff()} damage.\nAll 0{energyPrefix:energyIcons(1)} Attack cards deal {Kuuga:diff()} more damage.\nWhenever you switch [gold]Stances[/gold], if this card has not been [gold]Exhausted[/gold], return it to your hand."),
("KOMEIJIKOISHI-DANMAKU_ENDLESS_MIRACLE_KOISHI.title", "Danmaku Miracle"),
("KOMEIJIKOISHI-DANMAKU_ENDLESS_MIRACLE_KOISHI.description", "This turn, [gold]Danmaku[/gold] cards you play are played one additional time."),
("KOMEIJIKOISHI-SECOND_NEED_KOISHI.title", "Instinctive Second Need"),
("KOMEIJIKOISHI-SECOND_NEED_KOISHI.description", "Whenever you switch [gold]Stances[/gold], gain {BlockAmount:diff()} Block."),
("KOMEIJIKOISHI-ATTACHMENT_SAFE_HAVEN_UNCONSCIOUS_KOISHI.title", "Memory Safe Haven"),
("KOMEIJIKOISHI-ATTACHMENT_SAFE_HAVEN_UNCONSCIOUS_KOISHI.description", "Gain {Block:diff()} Block."),
("KOMEIJIKOISHI-UNCONSCIOUS_GENE_KOISHI.title", "Unconscious Gene"),
("KOMEIJIKOISHI-UNCONSCIOUS_GENE_KOISHI.description", "Deal {Damage:diff()} damage.\nAll cards in your hand gain [gold]Unconscious[/gold].\nWhenever you play an [gold]Unconscious[/gold] card, this card costs {Reduction:diff()} less this combat."),
("KOMEIJIKOISHI-LOOKING_GLASS_SELF_KOISHI.title", "Looking-Glass Self"),
("KOMEIJIKOISHI-LOOKING_GLASS_SELF_KOISHI.description", "For each card in your exhaust pile, gain 1 [gold]Block[/gold]."),
("KOMEIJIKOISHI-KOISHIS_KNIFE_KOISHI.title", "Koishi's Knife"),
("KOMEIJIKOISHI-KOISHIS_KNIFE_KOISHI.description", "Deal {Damage:diff()} damage.\nCan be upgraded any number of times.\nOn [gold]Fatal[/gold], upgrade itself."),
("KOMEIJIKOISHI-IN_FREEDOM_KOISHI.title", "In Freedom"),
("KOMEIJIKOISHI-IN_FREEDOM_KOISHI.description", "Draw 1 card.\nChoose up to {Cards:diff()} card(s). They gain [gold]Unconscious[/gold], then discard them."),
("KOMEIJIKOISHI-IN_FREEDOM_KOISHI.selectionScreenPrompt", "Choose up to {Cards:diff()} card(s) to gain Unconscious and discard"),
("KOMEIJIKOISHI-UNINTENTIONAL_HARVEST_KOISHI.title", "Unintentional Harvest"),
("KOMEIJIKOISHI-UNINTENTIONAL_HARVEST_KOISHI.description", "Draw {Cards:diff()} card(s).\n[gold]Retain[/gold] your hand this turn."),
("KOMEIJIKOISHI-SPIRITUAL_DESTRUCTION_KOISHI.title", "Spiritual Destruction"),
("KOMEIJIKOISHI-SPIRITUAL_DESTRUCTION_KOISHI.description", "Automatically generate and play X {IfUpgraded:show:[gold]upgraded[/gold] }[gold]Yin-Yang Orb Danmaku[/gold].\nGenerate 2X [gold]Conscious Overflow[/gold] into your draw pile."),
("KOMEIJIKOISHI-KOMEIJI_DASH_KOISHI.title", "Komeiji Dash"),
("KOMEIJIKOISHI-KOMEIJI_DASH_KOISHI.description", "Deal {Damage:diff()} damage to all enemies."),
("KOMEIJIKOISHI-SUPER_REACTIVE_PERCEPTION_KOISHI.title", "Super Reactive Perception"),
("KOMEIJIKOISHI-SUPER_REACTIVE_PERCEPTION_KOISHI.description", "Deal {Damage:diff()} damage to all enemies.\nRandomly play 1 [gold]Unconscious[/gold] card from your hand."),
("KOMEIJIKOISHI-CASUAL_GAME_KOISHI.title", "Casual Game"),
("KOMEIJIKOISHI-CASUAL_GAME_KOISHI.description", "Draw {Cards:diff()} card(s).\nRandomly play 1 [gold]Unconscious[/gold] card from your hand."),
("KOMEIJIKOISHI-CONSCIOUS_COLLECTION_KOISHI.title", "Conscious Collection"),
("KOMEIJIKOISHI-CONSCIOUS_COLLECTION_KOISHI.description", "Draw {Cards:diff()} card(s).\nAdd 1 [gold]Conscious Overflow[/gold] to your [gold]hand[/gold]."),
("KOMEIJIKOISHI-UNDERGROUND_ROSE_KOISHI.title", "Underground Rose"),
("KOMEIJIKOISHI-UNDERGROUND_ROSE_KOISHI.description", "Whenever you switch [gold]Stances[/gold], generate and automatically play 1 [gold]Rose Danmaku[/gold]."),
("KOMEIJIKOISHI-CONSCIOUSNESS_SPIRAL_KOISHI.title", "Consciousness Spiral"),
("KOMEIJIKOISHI-CONSCIOUSNESS_SPIRAL_KOISHI.description", "At the start of your turn, add 1 [gold]Conscious Spin[/gold] to your hand."),
("KOMEIJIKOISHI-CONSCIOUSNESS_ROTATION_KOISHI.title", "Conscious Spin"),
("KOMEIJIKOISHI-CONSCIOUSNESS_ROTATION_KOISHI.description", "Switch your current [gold]Stance[/gold].\nThis card costs 1 more this combat.\nAfter being played, return it to your hand."),
("KOMEIJIKOISHI-PHILOSOPHY_OF_THE_HATED_KOISHI.title", "Philosophy of the Hated"),
("KOMEIJIKOISHI-PHILOSOPHY_OF_THE_HATED_KOISHI.description", "Whenever you enter [gold]Closed[/gold], automatically play 2 [gold]Unconscious[/gold] cards from your hand."),
("KOMEIJIKOISHI-SELFLESS_LOVE_KOISHI.title", "Selfless Love"),
("KOMEIJIKOISHI-SELFLESS_LOVE_KOISHI.description", "Whenever you generate 6 [gold]Danmaku[/gold] cards, draw 1 card."),
("KOMEIJIKOISHI-FLAW_OF_DN_A_KOISHI.title", "Flaw of DNA"),
("KOMEIJIKOISHI-FLAW_OF_DN_A_KOISHI.description", "All your Attack cards cost 0 and [gold]Exhaust[/gold] when played.\nAt the start of your turn, 0{energyPrefix:energyIcons(1)} Attack cards deal {Flaw:inverseDiff()} less damage."),
("KOMEIJIKOISHI-ANCESTORS_WATCHING_KOISHI.title", "Ancestors Watching"),
("KOMEIJIKOISHI-ANCESTORS_WATCHING_KOISHI.description", "For every 2 cards in your exhaust pile, all 0{energyPrefix:energyIcons(1)} Attack cards deal 1 more damage."),
("KOMEIJIKOISHI-SPRINKLE_STAR_HEART_KOISHI.title", "Sprinkle Star Heart"),
("KOMEIJIKOISHI-SPRINKLE_STAR_HEART_KOISHI.description", "Deal {Damage:diff()} damage.\nGenerate 1 [gold]Star Danmaku[/gold] and 1 [green]Heart Danmaku[/green] into your exhaust pile.\nPlay all [gold]Star Danmaku[/gold] and [green]Heart Danmaku[/green] in all piles."),
("KOMEIJIKOISHI-ROSE_RHAPSODY_PUNCH_KOISHI.title", "Rose Rhapsody Punch"),
("KOMEIJIKOISHI-ROSE_RHAPSODY_PUNCH_KOISHI.description", "Deal {Damage:diff()} damage.\nIf your hand contains at least 3 [gold]Unconscious[/gold] cards, deal this damage one additional time."),
("KOMEIJIKOISHI-MALLET_LOVE_SIGN_KOISHI.title", "Mallet Love Sign"),
("KOMEIJIKOISHI-MALLET_LOVE_SIGN_KOISHI.description", "Deal {Damage:diff()} damage {Repeat:diff()} times.\nWhenever this deals unblocked damage, gain {Energy:energyIcons()}."),
("KOMEIJIKOISHI-BRAMBLY_ROSE_GARDEN_KOISHI.title", "Brambly Rose Garden"),
("KOMEIJIKOISHI-BRAMBLY_ROSE_GARDEN_KOISHI.description", "Gain {ThornsPower:diff()} [gold]Thorns[/gold].\nAt the start of your turn, double your [gold]Thorns[/gold]."),
("KOMEIJIKOISHI-FREUDIAN_KOISHI.title", "Instinctive Freudian Theory"),
("KOMEIJIKOISHI-FREUDIAN_KOISHI.description", "For each [gold]Unconscious[/gold] card in your hand, gain {Block:diff()} [gold]Block[/gold]."),
("KOMEIJIKOISHI-CONFINED_INNOCENT_KOISHI.title", "Confined Innocent"),
("KOMEIJIKOISHI-CONFINED_INNOCENT_KOISHI.description", "Gain {Block:diff()} [gold]Block[/gold].\nWhenever you switch [gold]Stances[/gold], this card's [gold]Block[/gold] increases by {Magic:diff()} this combat."),
("KOMEIJIKOISHI-HEARTWARD_STRIKE_KOISHI.title", "Heartward Strike"),
("KOMEIJIKOISHI-HEARTWARD_STRIKE_KOISHI.description", "Deal {Damage:diff()} damage.\nPut {Cards:diff()} [gold]Unconscious[/gold] card(s) from your discard pile on top of your draw pile."),
("KOMEIJIKOISHI-HEARTWARD_STRIKE_KOISHI.selectionScreenPrompt", "Choose an Unconscious card to put on top of your draw pile"),
("KOMEIJIKOISHI-DEATH_DRIVE_KOISHI.title", "Instinctive Death Drive"),
("KOMEIJIKOISHI-DEATH_DRIVE_KOISHI.description", "Deal {Damage:diff()} damage {Repeat:diff()} times.\nWhenever you switch [gold]Stances[/gold], this card attacks 1 additional time this combat."),
("KOMEIJIKOISHI-BOUNDARY_HEART_KOISHI.title", "Boundary Heart"),
("KOMEIJIKOISHI-BOUNDARY_HEART_KOISHI.description", "Enter [gold]Closed[/gold].\nIf you are already in [gold]Closed[/gold], gain {Block:diff()} [gold]Block[/gold]."),
("KOMEIJIKOISHI-VOID_EXPANSION_KOISHI.title", "Void Expansion"),
("KOMEIJIKOISHI-VOID_EXPANSION_KOISHI.description", "Enter [gold]Bloom[/gold].\nIf you are already in [gold]Bloom[/gold], all 0{energyPrefix:energyIcons(1)} Attack cards deal {Magic:diff()} more damage."),
("KOMEIJIKOISHI-UNCONSCIOUS_EXPLOSION_KOISHI.title", "Unconscious Explosion"),
("KOMEIJIKOISHI-UNCONSCIOUS_EXPLOSION_KOISHI.description", "All other cards in your hand gain [gold]Unconscious[/gold]."),
("KOMEIJIKOISHI-SILENT_BOMBARDMENT_KOISHI.title", "Silent Bombardment"),
("KOMEIJIKOISHI-SILENT_BOMBARDMENT_KOISHI.description", "Deal {Damage:diff()} damage {Repeat:diff()} times.\nEnter [gold]Closed[/gold]."),
("KOMEIJIKOISHI-EMERGENCY_SPELL_CARD_KOISHI.title", "Emergency Spell Card"),
("KOMEIJIKOISHI-EMERGENCY_SPELL_CARD_KOISHI.description", "Add {Cards:diff()} random [gold]Danmaku[/gold] card(s) to your hand.\nAll 0{energyPrefix:energyIcons(1)} Attack cards deal {KuugaPower:diff()} less damage."),
("KOMEIJIKOISHI-INSTINCTIVE_FORM_KOISHI.title", "Instinctive Form"),
("KOMEIJIKOISHI-INSTINCTIVE_FORM_KOISHI.description", "At end of turn, play {InstinctiveFormPower:diff()} [gold]Unconscious[/gold] card(s)."),
("KOMEIJIKOISHI-L_W_KOISHI_FUMO_KOISHI.title", "LW Koishi Fumo"),
("KOMEIJIKOISHI-L_W_KOISHI_FUMO_KOISHI.description", "Gain {Energy:energyIcons()} energy."),
("KOMEIJIKOISHI-YOUMU_FUMO_KOISHI.title", "Youmu Fumo"),
("KOMEIJIKOISHI-YOUMU_FUMO_KOISHI.description", "Deal {Damage:diff()} damage {Repeat:diff()} times."),
("KOMEIJIKOISHI-FLANDRE_FUMO_KOISHI.title", "Flandre Fumo"),
("KOMEIJIKOISHI-FLANDRE_FUMO_KOISHI.description", "Deal {Damage:d} damage."),
("KOMEIJIKOISHI-REISEN_FUMO_KOISHI.title", "Reisen Fumo"),
("KOMEIJIKOISHI-REISEN_FUMO_KOISHI.description", "Very cute."),
("KOMEIJIKOISHI-SHION_FUMO_KOISHI.title", "Shion Fumo"),
("KOMEIJIKOISHI-SHION_FUMO_KOISHI.description", "Really cute."),
("KOMEIJIKOISHI-YUKARI_FUMO_KOISHI.title", "Yukari Fumo"),
("KOMEIJIKOISHI-YUKARI_FUMO_KOISHI.description", "Choose {FreeSpace} card(s) from your draw pile and add them to your hand."),
("KOMEIJIKOISHI-YUKARI_FUMO_KOISHI.selectionScreenPrompt", "Choose {FreeSpace} card(s) from your draw pile and add them to your hand."),
("KOMEIJIKOISHI-YUYUKO_FUMO_KOISHI.title", "Yuyuko Fumo"),
("KOMEIJIKOISHI-YUYUKO_FUMO_KOISHI.description", "Eat any number of cards in your hand."),
("KOMEIJIKOISHI-YUYUKO_FUMO_KOISHI.selectionScreenPrompt", "Eat any number of cards in your hand."),
("KOMEIJIKOISHI-OKINA_FUMO_KOISHI.title", "Okina Fumo"),
("KOMEIJIKOISHI-OKINA_FUMO_KOISHI.description", "Choose {FreeSpace} card(s) from your exhaust pile and add them to your hand."),
("KOMEIJIKOISHI-OKINA_FUMO_KOISHI.selectionScreenPrompt", "Choose {FreeSpace} card(s) from your exhaust pile and add them to your hand."),
("KOMEIJIKOISHI-CIRNO_FUMO_KOISHI.title", "Cirno Fumo"),
("KOMEIJIKOISHI-CIRNO_FUMO_KOISHI.description", "Gain {PlatingPower:diff()} [gold]Plated Armor[/gold]."),
("KOMEIJIKOISHI-KOGASA_FUMO_KOISHI.title", "Kogasa Fumo"),
("KOMEIJIKOISHI-KOGASA_FUMO_KOISHI.description", "Stun an enemy."),
("KOMEIJIKOISHI-TEWI_FUMO_KOISHI.title", "Tewi Fumo"),
("KOMEIJIKOISHI-TEWI_FUMO_KOISHI.description", "Gain {RollingBoulderPower:diff()} [gold]Rolling Boulder[/gold].\nAdd 10 [gold]Reisen Fumo[/gold] to your hand."),
("KOMEIJIKOISHI-REIMU_FUMO_KOISHI.title", "Reimu Fumo"),
("KOMEIJIKOISHI-REIMU_FUMO_KOISHI.description", "Deal {Damage:diff()} damage {Repeat:diff()} times.\nLose 100 [gold]Gold[/gold].\nAfter being played, return it to your hand."),
("KOMEIJIKOISHI-MARISA_FUMO_KOISHI.title", "Marisa Fumo"),
("KOMEIJIKOISHI-MARISA_FUMO_KOISHI.description", "Deal {Damage:diff()} damage to all enemies.\nAll 0{energyPrefix:energyIcons(1)} Attack cards deal {KuugaPower:diff()} less damage."),
("KOMEIJIKOISHI-YUUKA_FUMO_KOISHI.title", "Yuuka Fumo"),
("KOMEIJIKOISHI-YUUKA_FUMO_KOISHI.description", "Heal {Heal:diff()} HP."),
("KOMEIJIKOISHI-NUE_FUMO_KOISHI.title", "Nue Fumo"),
("KOMEIJIKOISHI-NUE_FUMO_KOISHI.description", "Randomize the costs of all cards in your hand until end of turn.\nIt seems to play itself."),
("KOMEIJIKOISHI-GIFT_YOU_FUMO_KOISHI.title", "Gift You Fumo"),
("KOMEIJIKOISHI-GIFT_YOU_FUMO_KOISHI.description", "Give an ally a {IfUpgraded:show:[gold]genuine[/gold] }[gold]Fumo[/gold]."),
("KOMEIJIKOISHI-PERFECT_MIND_CONTROL_KOISHI.title", "Perfect Mind Control"),
("KOMEIJIKOISHI-PERFECT_MIND_CONTROL_KOISHI.description", "The next X{IfUpgraded:show:[gold]+1[/gold]} [gold]Unconscious[/gold] card(s) you draw are automatically played."),
("KOMEIJIKOISHI-HUA_KAI_KOISHI.title", "Blooming Flower"),
("KOMEIJIKOISHI-HUA_KAI_KOISHI.description", "Give a random ally 1 stack of a [purple]Ko[/purple][green]ishi[/green]-exclusive power."),
("KOMEIJIKOISHI-IDS_SHIKIGAMI_KOISHI.title", "Id Shikigami"),
("KOMEIJIKOISHI-IDS_SHIKIGAMI_KOISHI.description", "Generate 2X {IfUpgraded:show:[gold]upgraded[/gold] }Skill cards into your draw pile."),
("KOMEIJIKOISHI-LOST_IN_FLOWER_FIELD_KOISHI.title", "Lost in the Flower Field"),
("KOMEIJIKOISHI-LOST_IN_FLOWER_FIELD_KOISHI.description", "Generate {GenerateAmount:diff()} random cards into your exhaust pile. They cost 0 this combat.\nAt the start of your turn, add {RetrieveAmount:diff()} of them to your hand."),
("KOMEIJIKOISHI-MISHAGUJI_PILLAR_KOISHI.title", "Mishaguji Pillar"),
("KOMEIJIKOISHI-MISHAGUJI_PILLAR_KOISHI.description", "Deal {Damage:diff()} damage.\nAdd a copy of this card to your hand.\nWhen drawn, automatically play it."),
("KOMEIJIKOISHI-YIN_YANG_GHOST_GOD_ORB_KOISHI.title", "Yin-Yang Ghost God Orb"),
("KOMEIJIKOISHI-YIN_YANG_GHOST_GOD_ORB_KOISHI.description", "Deal {Damage:diff()} damage. For each enemy, deal this damage one additional time. If there is only one enemy, play for free and deal {LoneEnemyMultiplier}x damage."),
("KOMEIJIKOISHI-EXPLOSIVE_RED_FROG_KOISHI.title", "Explosive Red Frog"),
("KOMEIJIKOISHI-EXPLOSIVE_RED_FROG_KOISHI.description", "Apply {JiasuiPower:diff()} [gold]Evil Omen[/gold], then trigger [gold]Evil Omen[/gold] once."),
("KOMEIJIKOISHI-KUUGA_SPEEDNOCLIP_KOISHI.title", "Kuuga Speednoclip"),
("KOMEIJIKOISHI-KUUGA_SPEEDNOCLIP_KOISHI.description", "Deal {CalculatedDamage:diff()} damage {Repeat:diff()} times.\nAdd {ExtraDamage:diff()} times your positive [gold]Kuuga[/gold] stacks to this card's damage."),
("KOMEIJIKOISHI-RANDOM_STRIKE_KOISHI.title", "Random Strike"),
("KOMEIJIKOISHI-RANDOM_STRIKE_KOISHI.description", "Randomly deal {Damage:diff()} damage {Repeat:diff()} times."),
("KOMEIJIKOISHI-KEEPER_OF_IMAGINARY_PERSONALITY_KOISHI.title", "Imaginary Keeper"),
("KOMEIJIKOISHI-KEEPER_OF_IMAGINARY_PERSONALITY_KOISHI.description", "Randomly exhaust a total of {ExhaustCards:diff()} cards from your hand, draw pile, and discard pile.\nIf {ExhaustCards:diff()} cards were exhausted, gain {Energy:energyIcons()} and draw {Cards:diff()} cards.\nOtherwise, exhaust this card."),
])
translations["cards.json"] = cards

relics = ordered([
("KOMEIJIKOISHI-KOISHI_STARTER_RELIC.title", "Mr. Hat"),
("KOMEIJIKOISHI-KOISHI_STARTER_RELIC.description", "At the end of your turn, randomly play a card with [gold]Unconscious[/gold] from your hand."),
("KOMEIJIKOISHI-KOISHI_STARTER_RELIC.flavor", "Mr. Hat is my good friend."),
("KOMEIJIKOISHI-KOISHI_ANICENT_RELIC.title", "Mr. Hat with Roses"),
("KOMEIJIKOISHI-KOISHI_ANICENT_RELIC.description", "At the end of your turn, randomly play a card with [gold]Unconscious[/gold] from your hand. Whenever you play a card with [gold]Unconscious[/gold], gain 1 [gold]Thorns[/gold]."),
("KOMEIJIKOISHI-KOISHI_ANICENT_RELIC.flavor", "A good friend brought some flowers for Mr. Hat."),
("SEA_GLASS.KOMEIJIKOISHI-KOISHI_CHARACTER.title", "Rainbow Goo-Goo Stone"),
("KOMEIJIKOISHI-LING_YI_DIAN_HUA_RELIC.title", "Spirit Phone"),
("KOMEIJIKOISHI-LING_YI_DIAN_HUA_RELIC.description", "On pickup, choose {Cards} cards in your deck. Enchant them with [gold]At Ease[/gold]."),
("KOMEIJIKOISHI-LING_YI_DIAN_HUA_RELIC.flavor", "\"Hello, hello, this is Koishi! I'm behind you right now~\""),
("KOMEIJIKOISHI-SATORI_BERET_KOISHI.title", "Satori's Beret"),
("KOMEIJIKOISHI-SATORI_BERET_KOISHI.description", "The first time you enter [gold]Bloom[/gold] each combat, draw {Cards} additional card(s) and gain {Energy:energyIcons()}."),
("KOMEIJIKOISHI-SATORI_BERET_KOISHI.flavor", "It radiates a mysterious confidence."),
("KOMEIJIKOISHI-RINS_CART_KOISHI.title", "Rin's Cart"),
("KOMEIJIKOISHI-RINS_CART_KOISHI.description", "Whenever a creature dies, draw {Cards} card(s)."),
("KOMEIJIKOISHI-RINS_CART_KOISHI.flavor", "Rin loves collecting corpses and playing with them. Lady Ran of the Yakumo family once complained about it."),
("KOMEIJIKOISHI-OKUUS_SECRET_EYE_KOISHI.title", "Okuu's Secret Eye"),
("KOMEIJIKOISHI-OKUUS_SECRET_EYE_KOISHI.description", "For each {Energy}{energyPrefix:energyIcons(1)} spent, deal [blue]{Damage}[/blue] damage to a random enemy."),
("KOMEIJIKOISHI-OKUUS_SECRET_EYE_KOISHI.flavor", "A hell raven can master this power perfectly. In theory, she is extremely dangerous, but fortunately she is also an idiot."),
("KOMEIJIKOISHI-MASK_OF_HOPE_RELIC.title", "Mask of Hope"),
("KOMEIJIKOISHI-MASK_OF_HOPE_RELIC.description", "At the start of each combat, the first card you play costs 0."),
("KOMEIJIKOISHI-MASK_OF_HOPE_RELIC.flavor", "I picked this up."),
("KOMEIJIKOISHI-FUMO_CARD_RELIC_KOISHI.title", "Fumo Card"),
("KOMEIJIKOISHI-FUMO_CARD_RELIC_KOISHI.description", "At the start of each combat, add {Cards} random [gold]Fumo[/gold] card(s) to your hand."),
("KOMEIJIKOISHI-FUMO_CARD_RELIC_KOISHI.flavor", "The outside world's trendiest card! They say it sold out everywhere!"),
("KOMEIJIKOISHI-ROSE_BOUQUET_KOISHI.title", "Rose Bouquet"),
("KOMEIJIKOISHI-ROSE_BOUQUET_KOISHI.description", "At the start of each combat, all 0{energyPrefix:energyIcons(1)} cards deal [blue]{Damage}[/blue] more damage."),
("KOMEIJIKOISHI-ROSE_BOUQUET_KOISHI.flavor", "If you want it, come take it yourself."),
("KOMEIJIKOISHI-IDOLS_MICROPHONE_KOISHI.title", "Idol's Microphone"),
("KOMEIJIKOISHI-IDOLS_MICROPHONE_KOISHI.description", "The first [gold]Unconscious[/gold] card you play each turn returns to your hand."),
("KOMEIJIKOISHI-IDOLS_MICROPHONE_KOISHI.flavor", "Koishi really does have idol potential."),
("KOMEIJIKOISHI-DIM_LIGHT_CANDLE_KOISHI.title", "Dim Light Candle"),
("KOMEIJIKOISHI-DIM_LIGHT_CANDLE_KOISHI.description", "Whenever a card is [gold]Exhausted[/gold], heal [green]{Heal}[/green] HP. Triggers up to [blue]6[/blue] times each combat."),
("KOMEIJIKOISHI-DIM_LIGHT_CANDLE_KOISHI.flavor", "It seems like it could sit on Mr. Hat..."),
("KOMEIJIKOISHI-SUWAKOS_HAT_KOISHI.title", "Suwako's Hat"),
("KOMEIJIKOISHI-SUWAKOS_HAT_KOISHI.description", "Cards you draw have their costs randomized. At the start of each turn, choose [blue]{Cards}[/blue] card(s) from your draw pile and add them to your hand."),
("KOMEIJIKOISHI-SUWAKOS_HAT_KOISHI.selectionScreenPrompt", "Choose a card to add to your hand."),
("KOMEIJIKOISHI-SUWAKOS_HAT_KOISHI.flavor", "The moment she sees you, she puts a hat on you."),
("KOMEIJIKOISHI-ONBASHIRA_KOISHI.title", "Onbashira"),
("KOMEIJIKOISHI-ONBASHIRA_KOISHI.description", "At the start of combat, add [blue]{Cards}[/blue] [gold]Onbashira[/gold] to your draw pile."),
("KOMEIJIKOISHI-ONBASHIRA_KOISHI.flavor", "A terrifying power. Anyone hit by it is too scared to speak."),
("KOMEIJIKOISHI-TINY_WHITE_SNAKE_KOISHI.title", "Tiny White Snake"),
("KOMEIJIKOISHI-TINY_WHITE_SNAKE_KOISHI.description", "Every [blue]{Turns}[/blue] turns, all enemies lose [red]{StrengthPower}[/red] [gold]Strength[/gold]."),
("KOMEIJIKOISHI-TINY_WHITE_SNAKE_KOISHI.flavor", "Does this really count as tiny?"),
("KOMEIJIKOISHI-KANAKOS_SHIMENAWA_KOISHI.title", "Kanako's Shimenawa"),
("KOMEIJIKOISHI-KANAKOS_SHIMENAWA_KOISHI.description", "Whenever you play a card, deal [blue]{Damage}[/blue] damage to all enemies."),
("KOMEIJIKOISHI-KANAKOS_SHIMENAWA_KOISHI.flavor", "Why are counterfeit goods being sold?"),
("KOMEIJIKOISHI-FROG_CLOTHES_KOISHI.title", "Frog Clothes"),
("KOMEIJIKOISHI-FROG_CLOTHES_KOISHI.description", "If you have not played any cards this turn, heal [blue]{Heal}[/blue] HP at end of turn."),
("KOMEIJIKOISHI-FROG_CLOTHES_KOISHI.flavor", "After putting it on, you feel like croaking."),
("KOMEIJIKOISHI-NUCLEAR_MANAGEMENT_MANUAL_KOISHI.title", "Nuclear Manual"),
("KOMEIJIKOISHI-NUCLEAR_MANAGEMENT_MANUAL_KOISHI.description", "At end of turn, randomly [gold]Exhaust[/gold] [blue]{Cards}[/blue] card(s) in your hand. Whenever you have exhausted [blue]{ExhaustThreshold}[/blue] cards in total, gain a relic at the end of combat."),
("KOMEIJIKOISHI-NUCLEAR_MANAGEMENT_MANUAL_KOISHI.flavor", "Rule one: do not let an idiot follow the instructions."),
("KOMEIJIKOISHI-FROG_CARD_KOISHI.title", "Frog Card"),
("KOMEIJIKOISHI-FROG_CARD_KOISHI.description", "On pickup, add [blue]{Cards}[/blue] [gold]Explosive Red Frog[/gold] to your deck."),
("KOMEIJIKOISHI-FROG_CARD_KOISHI.flavor", "Who lets frogs self-destruct!?"),
("KOMEIJIKOISHI-MOUNTAIN_GODS_BLESSING_KOISHI.title", "Mountain God's Blessing"),
("KOMEIJIKOISHI-MOUNTAIN_GODS_BLESSING_KOISHI.description", "At the start of your turn, gain {Energy:energyIcons()}. At end of turn, if your hand has [blue]{HandThreshold}[/blue] or fewer cards, take [red]{Damage}[/red] damage."),
("KOMEIJIKOISHI-MOUNTAIN_GODS_BLESSING_KOISHI.flavor", "A little heavy."),
("KOMEIJIKOISHI-MIRACLE_GOHEI_KOISHI.title", "Miracle Gohei"),
("KOMEIJIKOISHI-MIRACLE_GOHEI_KOISHI.description", "On pickup, choose [blue]{Cards}[/blue] card(s). Enchant them with [gold]Miracle[/gold]."),
("KOMEIJIKOISHI-MIRACLE_GOHEI_KOISHI.flavor", "They say one used by a shrine maiden sells more easily."),
("KOMEIJIKOISHI-MIKOS_BOW_KOISHI.title", "Miko's Bow"),
("KOMEIJIKOISHI-MIKOS_BOW_KOISHI.description", "On pickup, choose [blue]{Cards}[/blue] card(s). Enchant them with [gold]Flying[/gold]."),
("KOMEIJIKOISHI-MIKOS_BOW_KOISHI.flavor", "They say many people use this to recognize Reimu."),
("KOMEIJIKOISHI-MIKO_BLESSING_KOISHI.title", "Miko Blessing"),
("KOMEIJIKOISHI-MIKO_BLESSING_KOISHI.description", "Each combat, prevent the first [blue]{Immunities}[/blue] instances of damage greater than [blue]{DamageThreshold}[/blue]."),
("KOMEIJIKOISHI-MIKO_BLESSING_KOISHI.flavor", "For just 5000 yen, you can receive the Hakurei shrine maiden's blessing!"),
("KOMEIJIKOISHI-HAKUREI_TORII_KOISHI.title", "Hakurei Torii"),
("KOMEIJIKOISHI-HAKUREI_TORII_KOISHI.description", "When you take less than [blue]{DamageThreshold}[/blue] damage, reduce it to 0 and heal [blue]{Heal}[/blue] HP."),
("KOMEIJIKOISHI-HAKUREI_TORII_KOISHI.flavor", "A tiny torii model with the power to ward off calamity."),
("KOMEIJIKOISHI-YIN_YANG_GHOST_GOD_ORB_RELIC_KOISHI.title", "Yin-Yang Ghost God Orb"),
("KOMEIJIKOISHI-YIN_YANG_GHOST_GOD_ORB_RELIC_KOISHI.description", "On pickup, add an upgraded [gold]Yin-Yang Ghost God Orb[/gold] to your deck."),
("KOMEIJIKOISHI-YIN_YANG_GHOST_GOD_ORB_RELIC_KOISHI.flavor", "Danmaku that is almost impossible to withstand!"),
("KOMEIJIKOISHI-MINI_SAISEN_BOX_KOISHI.title", "Mini Offering Box"),
("KOMEIJIKOISHI-MINI_SAISEN_BOX_KOISHI.description", "No longer gain Gold. Damage you deal and Block you gain are increased by [blue]{BonusPercent}[/blue]%."),
("KOMEIJIKOISHI-MINI_SAISEN_BOX_KOISHI.flavor", "She gave it to you so you could ask others to put money in it."),
("KOMEIJIKOISHI-RED_TIE_KOISHI.title", "Red Tie"),
("KOMEIJIKOISHI-RED_TIE_KOISHI.description", "On pickup, transform all Attack cards in your deck into [gold]Yin-Yang Orb Danmaku[/gold] and enchant them with [gold]Miracle[/gold]."),
("KOMEIJIKOISHI-RED_TIE_KOISHI.flavor", "Something Reimu always keeps with her. Please protect it well."),
("KOMEIJIKOISHI-EXORCISM_AMULET_KOISHI.title", "Exorcism Amulet"),
("KOMEIJIKOISHI-EXORCISM_AMULET_KOISHI.description", "When you draw a [green]Status[/green] or [red]Curse[/red], exhaust it and draw [blue]{Cards}[/blue] card(s)."),
("KOMEIJIKOISHI-EXORCISM_AMULET_KOISHI.flavor", "An amulet no calamity can pierce."),
("KOMEIJIKOISHI-FREE_GOHEI_KOISHI.title", "Free Gohei"),
("KOMEIJIKOISHI-FREE_GOHEI_KOISHI.description", "Cards that cost [blue]{CostThreshold}[/blue] or more cost 1 less. You can play at most [blue]{AttackLimit}[/blue] Attack cards each turn."),
("KOMEIJIKOISHI-FREE_GOHEI_KOISHI.flavor", "Reimu always thought a gohei that could exterminate things by itself would be convenient."),
("KOMEIJIKOISHI-FADED_MIKO_CLOTHES_KOISHI.title", "Faded Miko Clothes"),
("KOMEIJIKOISHI-FADED_MIKO_CLOTHES_KOISHI.description", "Gain {Energy:energyIcons()}. Each combat, after taking damage [blue]{DamageThreshold}[/blue] times, this becomes disabled."),
("KOMEIJIKOISHI-FADED_MIKO_CLOTHES_KOISHI.flavor", "Why are you carrying this around!?"),
("KOMEIJIKOISHI-KOMAINU_STONE_CARVING_KOISHI.title", "Komainu Stone Carving"),
("KOMEIJIKOISHI-KOMAINU_STONE_CARVING_KOISHI.description", "At the start of combat, gain [blue]{GuardianPower}[/blue] [gold]Guardian[/gold]."),
("KOMEIJIKOISHI-KOMAINU_STONE_CARVING_KOISHI.flavor", "She will always protect you."),
])
translations["relics.json"] = relics

ancients = ordered([
("DARV.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.char", "[i][font_size=22]Koishi passes by unconsciously.[/font_size][/i]"),
("DARV.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.next", "Continue"),
("DARV.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-1.ancient", "Hey! Strange girl, what're ya doing?"),
("DARV.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.ancient", "Koishi, good to see ya again. Take a gift before ya go."),
("DARV.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.ancient", "Koishi, why're ya going to the top of the Spire?"),
("DARV.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.next", "Respond"),
("DARV.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.char", "I don't know. I just suddenly got here!"),
("DARV.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.next", "Continue"),
("DARV.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-2.ancient", "My treasures end up here for reasons I don't understand either."),
("NEOW.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.char", "What a big fish."),
("NEOW.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.next", "Continue"),
("NEOW.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-1.ancient", "[sine]...satori... youkai...[/sine]"),
("NEOW.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.ancient", "[sine]...adventure... defeat... the Architect...[/sine]"),
("NEOW.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.next", "Continue"),
("NEOW.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-1r.char", "Of course!"),
("NEOW.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.ancient", "[sine]...again... satori youkai...[/sine]"),
("NEOW.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.next", "Question"),
("NEOW.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.char", "Huh? Why am I back again?"),
("NEOW.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.next", "Continue"),
("NEOW.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-2.ancient", "[sine]...these... help... adventure...[/sine]"),
("NONUPEIPE.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.ancient", "Cute girl, let me make you even more beautiful."),
("NONUPEIPE.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.ancient", "I am never stingy with blessings for a cute girl."),
("NONUPEIPE.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.ancient", "If you are going to meet the Architect, you must have beautiful and deadly things."),
("NONUPEIPE.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.next", "Continue"),
("NONUPEIPE.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.char", "[i][font_size=22]Koishi accepts unconsciously.[/font_size][/i]"),
("OROBAS.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.ancient", "Satori youkai! Eyeballs! We are same!!"),
("OROBAS.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.next", "Continue"),
("OROBAS.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-1.char", "Can you read minds too?"),
("OROBAS.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.ancient", "Koishi! Adventuring again!!"),
("OROBAS.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.next", "Continue"),
("OROBAS.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-1r.char", "Mr. Big Eyeball! Hello!"),
("OROBAS.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.ancient", "Koishi! Why! Adventure!!"),
("OROBAS.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.next", "Respond"),
("OROBAS.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.char", "Hmm... I don't know?"),
("PAEL.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.ancient", "[thinky_dots]Strange girl, your heart is even calmer than mine...[/thinky_dots]"),
("PAEL.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.char", "[i][font_size=22]Koishi passes by, humming.[/font_size][/i]"),
("PAEL.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.next", "Continue"),
("PAEL.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-1r.ancient", "[thinky_dots]Perhaps you could be even quieter...[/thinky_dots]"),
("PAEL.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.char", "Mr. Dragon! Mr. Dragon!"),
("PAEL.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.next", "Continue"),
("PAEL.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.ancient", "[thinky_dots]So you can be this noisy...?[/thinky_dots]"),
("TANX.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.ancient", "GIRL! YOUR KNIFE HIDES KILLING INTENT!"),
("TANX.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.next", "Continue"),
("TANX.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-1.char", "Koishi doesn't know."),
("TANX.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.ancient", "GIRL! YOUR KNIFE NEEDS SHARPENING!"),
("TANX.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.ancient", "FIGHT ME, KOISHI KOMEIJI!"),
("TANX.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.next", "Step forward"),
("TANX.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.char", "[i][font_size=22]Koishi uses gorgeous danmaku.[/font_size][/i]"),
("TANX.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.next", "Continue"),
("TANX.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-2.ancient", "BARELY HURT! BUT WORTHY OF PRAISE!"),
("TEZCATARA.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.ancient", "Little one, are you lost?"),
("TEZCATARA.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.ancient", "Would you like some hot cocoa, little one?"),
("TEZCATARA.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.next", "Taste"),
("TEZCATARA.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-1r.char", "It's even better than my sister's hot cocoa!"),
("TEZCATARA.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.ancient", "Is there another cute little one like you?"),
("TEZCATARA.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.next", "Continue"),
("TEZCATARA.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.char", "Sister! My sister really is cute!"),
("VAKUU.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.ancient", "A girl from far away? I can help you."),
("VAKUU.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.next", "Continue"),
("VAKUU.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-1.char", "Scary-looking mister!"),
("VAKUU.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.ancient", "Will you sign this contract? Perhaps you could call your sister over to sign as well."),
("VAKUU.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.ancient", "These contracts can help your adventure, for only a small price."),
("VAKUU.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.next", "Respond"),
("VAKUU.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.char", "A contract? My sister said I shouldn't sign things carelessly."),
("VAKUU.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.next", "Continue"),
("VAKUU.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-2.ancient", "Your sister would accept this generous contract."),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0r.char", "Are you the Architect?"),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0r.next", "Continue"),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-1r.ancient", "A satori youkai? How rare."),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-1r.next", "Continue"),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-2r.char", "I'm here to beat you!"),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-2r.next", "Continue"),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-3r.ancient", "Go back where you belong."),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.char", "[i][font_size=22]Koishi stabs unconsciously.[/font_size][/i]"),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.next", "Continue"),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-1r.ancient", "Again? Go back."),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0r.ancient", "Satori youkai, return to where you belong!"),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0r.next", "Continue"),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1r.char", "My adventure isn't over yet!"),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1r.next", "Continue"),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-2r.ancient", "Then it should end now!"),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.3-0r.char", "[i][font_size=22]Koishi pokes unconsciously.[/font_size][/i]"),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.3-0r.next", "Continue"),
("THE_ARCHITECT.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.3-1r.ancient", "Annoying!"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.title", "Two Gods of Moriya"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.epithet", "Yasaka and Moriya"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.ANY.0-0r.ancient", "A worshipper?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.ANY.0-0r.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.ANY.0-0r.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.ANY.0-1r.ancient", "Did you bring any gifts?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.ANY.0-1r.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.ANY.1-0r.ancient", "Here to worship again? Take something with you."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.ANY.1-0r.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.ANY.1-0r.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.ANY.1-1r.ancient", "Have you seen another green-haired shrine maiden? Sanae ran away from home again..."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.ANY.1-1r.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.ANY.2-0.ancient", "You're asking what that thing on the mountain is? Oh, that's nuclear equipment."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.ANY.2-0.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.firstVisitEver.0-0.ancient", "A worshipper?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.firstVisitEver.0-0.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.firstVisitEver.0-0.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.firstVisitEver.0-1.ancient", "I thought Sanae had come back."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.firstVisitEver.0-1.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.firstVisitEver.0-1.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.ancient", "Isn't that Koishi from the Palace of the Earth Spirits? Why are you here?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.next", "Answer"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-1.char", "I want power like Okuu's!"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-1.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-2.ancient", "That is not something to play around with!"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-2.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.ancient", "Koishi, have you seen Sanae?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.next", "Answer"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-1r.char", "Huh? The green shrine maiden? I don't know."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-1r.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-2r.ancient", "Maybe we should ask the tengu..."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-2r.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.char", "Running away from home? My sister says I do that all the time too."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.ancient", "You should at least tell your family before doing that!"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-2.ancient", "I'm hungry, Kanako."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-2.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-2.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-3.ancient", "I'm hungry too!"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-3.next", "Offer"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-3.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-4.char", "This is the pudding my sister gave Koishi. [i][font_size=22](A bouncy eyeball wreathed in purple smoke.)[/font_size][/i]"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.0-0.ancient", "Iron one, stop right there."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.0-0.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.0-0.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.0-1.ancient", "You look rather unfortunate."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.0-1.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.1-0r.ancient", "Take these with you, and complete your wish with Moriya's blessing."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.1-0r.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.1-0r.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.1-1r.ancient", "If Sanae were here, she could perform the grand Moriya dance."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.1-1r.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.2-0.ancient", "Still not done? Have you seen a green-haired shrine maiden?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.2-0.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.2-0.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.2-1.ancient", "If you see her, tell her the two gods at home are begging her to come back."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.IRONCLAD.2-1.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.0-0.ancient", "When did you arrive!? Even the tengu didn't notice?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.0-0.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.0-0.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.0-1.ancient", "If you're here to worship, put down the knife first."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.0-1.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.1-0r.ancient", "Next time you can knock out the tengu, but leave the kappa alone."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.1-0r.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.1-0r.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.1-1r.ancient", "Have you seen a green-haired shrine maiden?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.1-1r.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.1-1r.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.1-2r.char", "[i][font_size=22]The Silent shakes her head.[/font_size][/i]"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.2-0.ancient", "Hey! Don't play with frogs! They are not throwing weapons!"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.2-0.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.2-0.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.2-1.ancient", "Take some things and go. If you see Sanae, remind her it's time to come home."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.SILENT.2-1.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.0-0.ancient", "A new kappa creation?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.0-0.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.0-0.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.0-1.char", "[i][font_size=22]<confused beeping>[/font_size][/i]"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.0-1.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.0-2.ancient", "What a curious creation."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.0-2.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.1-0r.ancient", "Even the kappa behind the mountain can't fix you? I'm getting more and more curious."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.1-0r.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.1-0r.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.1-1r.ancient", "Did the kappa do anything to you?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.1-1r.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.1-1r.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.1-2r.char", "[i][font_size=22]<unpleasant memory beeps>[/font_size][/i]"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.2-0.ancient", "Could Sanae's miracle power fix you?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.2-0.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.2-0.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.2-1.ancient", "If you see her, tell her: I! Am! Hungry!"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.DEFECT.2-1.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.0-0.ancient", "From Former Hell? Should we ask that cat to carry you back?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.0-0.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.0-0.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.0-1.char", "I'm on the road to revenge. What can you do for me?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.0-1.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.0-2.ancient", "Take whatever you like. Moriya's blessing."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.0-2.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.1-0r.ancient", "Is that big hand beside you your shikigami?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.1-0r.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.1-0r.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.1-1r.char", "It's my partner."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.2-0.ancient", "Back again? Still haven't succeeded in your revenge? Take some more."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.2-0.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.2-0.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.NECROBINDER.2-1.char", "Thanks."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.0-0.char", "I've come to worship!"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.0-0.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.0-1.ancient", "Finally, a normal... normal worshipper?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.0-1.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.0-1.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.0-2.ancient", "At least one..."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.0-2.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.1-0r.char", "[i][font_size=22]The Regent presents tribute.[/font_size][/i]"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.1-0r.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.1-1r.ancient", "Little king, thank you for your tribute. Moriya's blessing will always protect you."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.1-1r.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.1-1r.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.1-2r.ancient", "What an eye-opening fellow."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.1-2r.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.2-0.ancient", "The little king has returned."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.2-0.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.2-0.ancient.speaker", "Kanako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.2-1.ancient", "Have you seen a green-haired shrine maiden?"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.2-1.next", "Answer"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.2-1.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.2-2.char", "I've seen a green four-legged creature. It hopped around."),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.2-2.next", "Continue"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.2-3.ancient", "That was a frog!"),
("KOMEIJIKOISHI-MORIYA_TWO_GODS_KOISHI.talk.REGENT.2-3.ancient.speaker", "Suwako"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.title", "Reimu Hakurei"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.epithet", "Shrine Maiden of Paradise"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.ANY.0-0r.ancient", "Hey! You over there, what happened here?"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.ANY.1-0r.ancient", "Me? Many people from Gensokyo have wandered into this tower lately. I'm here to investigate."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.ANY.2-0.ancient", "You want my blessing first? At least put some money in the offering box."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.firstVisitEver.0-0.ancient", "Hey, you there. Stop for a moment. I need to ask you something."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.char", "Miss Reimu! Miss Reimu!"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-0.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.0-1.ancient", "Who are you?"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.ancient", "Satori youkai, if you have nothing to do, hurry back home!"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-0r.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-1r.char", "Koishi's adventure isn't over! Miss Reimu, do you want to come too?"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-1r.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.1-2r.ancient", "Marisa isn't here either. Bringing this one along should be fine."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.ancient", "Satori youkai, take this. The ones ahead are a bit dangerous."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-0.next", "Accept"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.KOMEIJIKOISHI-KOISHI_CHARACTER.2-1.char", "Thank you, Miss Reimu!"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.IRONCLAD.0-0.ancient", "You really do carry an ominous air."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.IRONCLAD.1-0r.ancient", "Starting fights at the slightest disagreement. You're very Gensokyo. Take this. It'll help."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.IRONCLAD.2-0.ancient", "You have deep ties with that punchable demon. Too bad I can't remove the curses it gave you."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.SILENT.0-0.ancient", "(Watches the Silent fly in and ambush her prey)"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.SILENT.0-0.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.SILENT.0-1.ancient", "Ambushes aren't a good habit."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.SILENT.1-0r.ancient", "Do you kill everything you see?"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.SILENT.1-0r.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.SILENT.1-1r.char", "......"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.SILENT.1-1r.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.SILENT.1-2r.ancient", "If you're mute, go see Eirin."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.SILENT.2-0.ancient", "You have a very bad aura. Did you touch something evil?"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.SILENT.2-0.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.SILENT.2-1.char", "......"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.SILENT.2-1.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.SILENT.2-2.ancient", "I shouldn't have asked."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.DEFECT.0-0.ancient", "What is this? Did the kappa build it?"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.DEFECT.0-0.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.DEFECT.0-1.char", "(Confused beeping)"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.DEFECT.1-0r.ancient", "You cleaned up all the bugs below? How diligent."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.DEFECT.1-0r.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.DEFECT.1-1r.char", "(Embarrassed beeping)"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.DEFECT.2-0.ancient", "Even the kappa can't fix you? What are you beeping about?!"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.DEFECT.2-0.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.DEFECT.2-1.char", "(Dejected beeping)"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.NECROBINDER.0-0.ancient", "Why are there so many people covered in curses here?"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.NECROBINDER.0-0.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.NECROBINDER.0-1.char", "These curses let me take revenge on the Architect!"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.NECROBINDER.0-1.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.NECROBINDER.0-2.ancient", "I doubt the Architect could trick me into stopping you."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.NECROBINDER.1-0r.ancient", "Take these from your friend. If you can take down the mastermind behind this incident, all the better."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.NECROBINDER.1-0r.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.NECROBINDER.1-1r.char", "Osty and I will kill him."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.NECROBINDER.2-0.ancient", "A book caused you all to become like this? There are too many dangerous things here."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.REGENT.0-0.ancient", "You look like a god tied to a chair."),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.REGENT.0-0.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.REGENT.0-1.char", "I am the future king!"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.REGENT.1-0r.ancient", "What are those two below you? Your attendants?"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.REGENT.1-0r.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.REGENT.1-1r.char", "They are my servants!"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.REGENT.2-0.char", "Shrine maiden, two gods are looking for you!"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.REGENT.2-0.next", "Continue"),
("KOMEIJIKOISHI-HAKUREI_REIMU_KOISHI.talk.REGENT.2-1.ancient", "Huh? Another incident?"),
])
translations["ancients.json"] = ancients


def write_json(filename, data):
    src = json.loads((ZHS / filename).read_text(encoding="utf-8-sig"), object_pairs_hook=OrderedDict)
    missing = [k for k in src.keys() if k not in data]
    extra = [k for k in data.keys() if k not in src]
    if missing or extra:
        raise SystemExit(f"{filename} key mismatch\nmissing={missing}\nextra={extra}")
    ENG.mkdir(parents=True, exist_ok=True)
    (ENG / filename).write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def long_name_options():
    rows = []
    for filename, data in translations.items():
        for key, value in data.items():
            if not key.endswith(".title"):
                continue
            letters = sum(1 for ch in value if ch.isalpha())
            if letters <= 20:
                continue
            options = {
                "Ultimate Unconscious Form": ["Unconscious Form", "Ultimate Unconscious", "Unconscious Avatar"],
                "Yin-Yang Orb Danmaku": ["Yin-Yang Orb", "Orb Danmaku", "Yin-Yang Shot"],
                "Unconscious Danmaku Attack": ["Unconscious Danmaku", "Auto Danmaku", "Mindless Barrage"],
                "Reaction: Youkai Polygraph": ["Youkai Polygraph", "Reaction Polygraph", "Polygraph"],
                "Unconscious Passage": ["Unconscious Pass", "Mindless Passage", "Unseen Passage"],
                "Mental Stellar Succession": ["Stellar Succession", "Mental Succession", "Stellar Relay"],
                "Koishi, Kokoro, and Unconscious": ["Koishi and Kokoro", "Kokoro and Koishi", "Unconscious Kokoro"],
                "Unintentional Danmaku": ["Accidental Danmaku", "Random Danmaku", "Unwilled Barrage"],
                "Consciousness Rotation": ["Mind Rotation", "Conscious Spin", "Mind Turn"],
                "Philosophy of the Hated": ["Hated Philosophy", "Hated One's Thought", "Hated Doctrine"],
                "Super Reactive Perception": ["Reactive Perception", "Super Perception", "Rapid Perception"],
                "Yin-Yang Ghost God Orb": ["Ghost God Orb", "Yin-Yang God Orb", "Spirit God Orb"],
                "Keeper of Imaginary Personality": ["Imaginary Keeper", "Persona Keeper", "Fantasy Persona"],
                "Nuclear Management Manual": ["Nuclear Manual", "Reactor Manual", "Okuu Manual"],
                "Mountain God's Blessing": ["Mountain Blessing", "God's Blessing", "Moriya Blessing"],
                "Shrine Maiden's Blessing": ["Miko Blessing", "Hakurei Blessing", "Maiden Blessing"],
                "Komainu Stone Carving": ["Komainu Carving", "Stone Komainu", "Komainu Statue"],
                "Lost in the Flower Field": ["Flower Field", "Lost in Flowers", "Flowerfield Lost"],
            }.get(value, [])
            rows.append((filename, key, value, letters, options))

    lines = [
        "# English Long Name Review",
        "",
        "Names below exceed 20 English letters (spaces and punctuation ignored). Pick one of the shorter options or provide your own.",
        "",
        "| File | Key | Current name | Letters | Shortening options |",
        "| --- | --- | --- | ---: | --- |",
    ]
    for filename, key, value, letters, options in rows:
        opt = "<br>".join(options) if options else "Needs manual choice"
        lines.append(f"| `{filename}` | `{key}` | {value} | {letters} | {opt} |")
    lines.extend([
        "",
        "## Names Not Taken Directly From File Names",
        "",
        "These names intentionally follow the Chinese meaning instead of the class/file name, or use a shorter display name. If you prefer filename-style English for any of them, use the option in the last column.",
        "",
        "| File | Key | Current name | Filename-style option | Note |",
        "| --- | --- | --- | --- | --- |",
        "| `cards.json` | `KOMEIJIKOISHI-DISINTEGRATING_CONSCIOUSNESS_CAPTURE_KOISHI.title` | Consciousness Capture | Disintegrating Consciousness Capture | Current name is shorter; filename-style name is very long. |",
        "| `cards.json` | `KOMEIJIKOISHI-BIG_HUG_KOISHI.title` | Komeiji Big Hug | Big Hug | Current name follows the Chinese title more closely. |",
        "| `cards.json` | `KOMEIJIKOISHI-ATTACHMENT_SAFE_HAVEN_UNCONSCIOUS_KOISHI.title` | Memory Safe Haven | Attachment Safe Haven Unconscious | Current name follows the Chinese meaning and is much cleaner. |",
        "| `cards.json` | `KOMEIJIKOISHI-FREUDIAN_KOISHI.title` | Freudian Theory | Freudian | Current name expands the file name into a readable card title. |",
        "| `cards.json` | `KOMEIJIKOISHI-HUA_KAI_KOISHI.title` | Blooming Flower | Hua Kai | File name is pinyin; current name translates the Chinese meaning. |",
        "| `relics.json` | `KOMEIJIKOISHI-KOISHI_STARTER_RELIC.title` | Mr. Hat | Koishi Starter | Current name follows the Chinese title; filename-style would be generic. |",
        "| `relics.json` | `KOMEIJIKOISHI-KOISHI_ANICENT_RELIC.title` | Mr. Hat with Roses | Koishi Ancient | Current name follows the Chinese title; filename-style would be generic. |",
        "| `relics.json` | `SEA_GLASS.KOMEIJIKOISHI-KOISHI_CHARACTER.title` | Rainbow Goo-Goo Stone | Sea Glass | Current name follows the Chinese title instead of the base relic name. |",
        "| `relics.json` | `KOMEIJIKOISHI-LING_YI_DIAN_HUA_RELIC.title` | Spirit Phone | Ling Yi Dian Hua | File name is pinyin; current name translates the Chinese meaning. |",
        "| `relics.json` | `KOMEIJIKOISHI-MIKOS_BOW_KOISHI.title` | Shrine Maiden's Bow | Miko's Bow | Both are valid; filename-style is shorter. |",
        "| `relics.json` | `KOMEIJIKOISHI-MIKO_BLESSING_KOISHI.title` | Shrine Maiden's Blessing | Miko Blessing | Filename-style is shorter and already listed as a long-name option. |",
        "| `powers.json` | `KOMEIJIKOISHI-KOISHI_KOKORO_POWER.title` | Kokoro's Mask | Koishi Kokoro | Current name follows the effect/theme rather than the class name. |",
        "| `powers.json` | `KOMEIJIKOISHI-PERFECT_MIND_CONTROL_POWER.title` | Mind Control | Perfect Mind Control | Current name is shorter; filename-style matches the card. |",
        "| `powers.json` | `KOMEIJIKOISHI-JIASUI_POWER.title` | Evil Omen | Jiasui | File name is pinyin; current name translates the Chinese meaning. |",
    ])
    LONG_NAMES.write_text("\n".join(lines) + "\n", encoding="utf-8")


for filename, data in translations.items():
    write_json(filename, data)
long_name_options()

print("Generated English localization:")
for filename in sorted(translations):
    print(f" - {filename}: {len(translations[filename])} keys")
print(f"Long-name review: {LONG_NAMES}")
